config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  path_names: {sign_up: ''}
  
  get 'info_album_view', to: 'operation_controller#info_album_view'
  get 'info_composition_view', to: 'operation_controller#info_composition_view'
  get 'info_storage_view', to: 'operation_controller#info_storage_view'
  get 'composition_lists_report', to: 'operation_controller#composition_lists_report'
  get 'storage_lists_report', to: 'operation_controller#storage_lists_report'
  get 'artist_lists_report', to: 'operation_controller#artist_lists_report'
  get 'info_person_view', to: 'operation_controller#info_person_view'
  get 'info_artist_view', to: 'operation_controller#info_artist_view'
  get 'info_label_view', to: 'operation_controller#info_label_view'
  
  get 'search', to: 'operation_controller#search'
  get 'composition_search', to: 'operation_controller#composition_search'
  get 'album_search', to: 'operation_controller#album_search'
  get 'music_storage_search', to: 'operation_controller#music_storage_search'
  get 'music_storage_search_country', to: 'operation_controller#music_storage_search_country'
  get 'artist_search', to: 'operation_controller#artist_search'
  
#  get 'operation_controller/info_composition_view'
  
    root to: 'operation_controller#search'
    
  resources :person, :artist, :artist_list 
  post '/people' => 'person#create'
  post '/artists' => 'artist#create'
  post '/artist_lists' => 'artist_list#create'
  
  resources :label, :album, :composition
  post '/labels' => 'label#create'
  post '/albums' => 'album#create'
  post '/compositions' => 'composition#create'
  
  resources :composition_list, :music_storage, :storage_list
  post '/composition_lists' => 'composition_list#create'
  post '/music_storages' => 'music_storage#create'
  post '/storage_lists' => 'storage_list#create'
  
  get 'success', to: 'operation_controller#success'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/operation_controller_controller.rb
# frozen_string_literal: true

class OperationControllerController < ApplicationController
   
    
    def info_composition_view
        composition_id=params[:composition_id].to_i
        @composition = Composition.find_by_id(composition_id)
        p 3
    end
      
    def info_album_view
        album_id=params[:album_id].to_i
        @album = Album.find_by_id(album_id)
        p 3
    end  
      
    def info_storage_view
        music_storage_id=params[:music_storage_id].to_i
        @music_storage = MusicStorage.find_by_id(music_storage_id)
        p 3
    end
    
    def info_artist_view
        artist_id=params[:artist_id].to_i
        @artist = Artist.find_by_id(artist_id)
        p 3
    end
    
    def info_person_view
        person_id=params[:person_id].to_i
        @person = Person.find_by_id(person_id)
        p 3
    end
    
    def info_label_view
        label_id=params[:label_id].to_i
        @label = Label.find_by_id(label_id)
        p 3
    end
    
    def composition_lists_report
#        @composition_lists = CompositionList.joins(:person, :artist, composition: :genre, album: [ :album_type, :label]).select("compositions.name as 'composition_name', compositions.duration, compositions.release_date, albums.name as 'album_name', artists.name as 'artist_name', people.first_name, people.last_name, composition_lists.position_number, composition_lists.id, album_types.name as 'album_type', genres.name as 'genre', labels.name as 'label'")
        @composition_lists = CompositionList.find_by_sql"SELECT compositions.name as 'composition_name', compositions.duration, compositions.release_date, albums.name as 'album_name', artists.name as 'artist_name', people.first_name, people.last_name, composition_lists.position_number, composition_lists.id, album_types.name as 'album_type', genres.name as 'genre', labels.name as 'label' FROM 'composition_lists' INNER JOIN 'people' ON 'people'.'id' = 'composition_lists'.'person_id' INNER JOIN 'artists' ON 'artists'.'id' = 'composition_lists'.'artist_id' INNER JOIN 'compositions' ON 'compositions'.'id' = 'composition_lists'.'composition_id' INNER JOIN 'genres' ON 'genres'.'id' = 'compositions'.'genre_id' INNER JOIN 'albums' ON 'albums'.'id' = 'composition_lists'.'album_id' INNER JOIN 'album_types' ON 'album_types'.'id' = 'albums'.'album_type_id' INNER JOIN 'labels' ON 'labels'.'id' = 'albums'.'label_id'"
    end
      
    def storage_lists_report
#        @storage_lists = StorageList.joins(music_storage: [:storage_type, :company], album: [ :album_type, :label]).select("albums.name as 'album_name', album_types.name as 'album_type', labels.name as 'label_name', music_storages.name as 'storage_name', storage_types.name as 'storage_type', companies.name as 'company_name', music_storages.rack, music_storages.shelf, music_storages.section, music_storages.cell, storage_lists.id, storage_lists.production_year")
        @storage_lists = StorageList.find_by_sql"SELECT albums.name as 'album_name', album_types.name as 'album_type', labels.name as 'label_name', music_storages.name as 'storage_name', storage_types.name as 'storage_type', companies.name as 'company_name', music_storages.rack, music_storages.shelf, music_storages.section, music_storages.cell, storage_lists.id, storage_lists.production_year FROM 'storage_lists' INNER JOIN 'music_storages' ON 'music_storages'.'id' = 'storage_lists'.'music_storage_id' INNER JOIN 'storage_types' ON 'storage_types'.'id' = 'music_storages'.'storage_type_id' INNER JOIN 'companies' ON 'companies'.'id' = 'music_storages'.'company_id' INNER JOIN 'albums' ON 'albums'.'id' = 'storage_lists'.'album_id' INNER JOIN 'album_types' ON 'album_types'.'id' = 'albums'.'album_type_id' INNER JOIN 'labels' ON 'labels'.'id' = 'albums'.'label_id'"
    end
    
    def artist_lists_report
#        @artist_lists = ArtistList.joins(:artist, person: :country).select("artists.name as 'artist_name', artists.type_band, artist_lists.debut_year, artist_lists.end_year, people.first_name, people.last_name, people.birth_date, people.death_date, countries.name as 'country_name', artist_lists.id")
        @artist_lists = ArtistList.find_by_sql"SELECT artists.name as 'artist_name', artists.type_band, artist_lists.debut_year, artist_lists.end_year, people.first_name, people.last_name, people.birth_date, people.death_date, countries.name as 'country_name', artist_lists.id FROM 'artist_lists' INNER JOIN 'artists' ON 'artists'.'id' = 'artist_lists'.'artist_id' INNER JOIN 'people' ON 'people'.'id' = 'artist_lists'.'person_id' INNER JOIN 'countries' ON 'countries'.'id' = 'people'.'country_id'"
    end
    
    def composition_search
p       request_name = params[:request_name]
p       date_from = params[:date_from]
p       date_to = params[:date_to]
        artist = params[:composition_artist_id]
        genre = params[:composition_genre_id]
        title = "Result of search among COMPOSITIONS with NAME request:\n" + request_name
        #compositions = CompositionList.joins(:composition, :artist).where( "compositions.name LIKE ? AND compositions.genre_id = ? AND artists.id = ? AND compositions.release_date >= ? AND compositions.release_date <= ? ", "%#{request_name}%", genre, artist, date_from, date_to ).group('compositions.id').select("compositions.name, compositions.duration as 'info', compositions.id")    
        compositions = CompositionList.find_by_sql "SELECT compositions.name, compositions.duration as 'info', compositions.id FROM 'composition_lists' INNER JOIN 'compositions' ON 'compositions'.'id' = 'composition_lists'.'composition_id' INNER JOIN 'artists' ON 'artists'.'id' = 'composition_lists'.'artist_id' WHERE (compositions.name LIKE '%"+request_name+"%' AND compositions.genre_id = '"+genre+"' AND artists.id = '"+artist+"' AND compositions.release_date >= '"+date_from+"' AND compositions.release_date <= '"+date_to+"' ) GROUP BY compositions.id"
        respond_to do |format|
            format.html
            format.json { render json: { result: compositions, title: title,  message: 'Nothing found by your request!' } }
        end
    end

    def artist_search
        request_name = params[:request_name]
        date_from = params[:date_from]
        date_to = params[:date_to]
        type = params[:artist_type]
        title = "Result of search among ARTISTS with NAME request:\n" + request_name
  #     artists = ArtistList.joins(:artist).where( "artists.name LIKE ?  AND artists.type_band = ? AND artist_lists.debut_year >= ? AND artist_lists.debut_year <= ?", "%#{request_name}%", type, date_from, date_to).group('artists.id').select("artists.name, artists.type_band as 'info', artists.id")
        artists = ArtistList.find_by_sql"SELECT artists.name, artists.type_band as 'info', artists.id FROM 'artist_lists' INNER JOIN 'artists' ON 'artists'.'id' = 'artist_lists'.'artist_id' WHERE (artists.name LIKE '%"+request_name+"%'  AND artists.type_band = '"+type+"' AND artist_lists.debut_year >= '"+date_from+"' AND artist_lists.debut_year <= '"+date_to+"') GROUP BY artists.id"
        respond_to do |format|
            format.html
            format.json { render json: { result: artists, title: title,  message: 'Nothing found by your request!' } }
        end
    end
    
    def album_search
        request_name = params[:request_name]
        date_from = params[:date_from]
        date_to = params[:date_to]
        artist = params[:album_artist_id]
        label = params[:album_label_id]
        title = "Result of search among ALBUMS with NAME request:\n" + request_name
p    #   albums = CompositionList.joins(:artist, :album).where( "albums.name LIKE ? AND  artists.id = ? AND albums.label_id = ? AND albums.release_date >= ? AND albums.release_date <=? ", "%#{request_name}%", artist, label, date_from, date_to ).group('albums.id').select("albums.name, albums.release_date as 'info', albums.id")
        albums= CompositionList.find_by_sql"SELECT albums.name, albums.release_date as 'info', albums.id FROM 'composition_lists' INNER JOIN 'artists' ON 'artists'.'id' = 'composition_lists'.'artist_id' INNER JOIN 'albums' ON 'albums'.'id' = 'composition_lists'.'album_id' WHERE (albums.name LIKE '%"+request_name+"%' AND  artists.id = '"+artist+"' AND albums.label_id = '"+label+"' AND albums.release_date >= '"+date_from+"' AND albums.release_date <='"+date_to+"' ) GROUP BY albums.id"
        respond_to do |format|
            format.html
            format.json { render json: { result: albums, title: title,  message: 'Nothing found by your request!' } }
        end
    end

    def music_storage_search
        request_name = params[:request_name]
        album = params[:music_storage_album_id]
        company = params[:music_storage_company_id]
        type = params[:music_storage_type_id]
        title = "Result of search among MUSIC STORAGES with NAME request:\n" + request_name
       # music_storages = StorageList.joins(:album, :music_storage).where( "music_storages.name LIKE ? AND albums.id = ? AND music_storages.storage_type_id = ? AND music_storages.company_id = ?", "%#{request_name}%", album, type, company).group('music_storages.id').select('music_storages.name, music_storages.id, music_storages.storage_type_id');
        music_storages = StorageList.find_by_sql"SELECT music_storages.name, music_storages.id, music_storages.storage_type_id FROM 'storage_lists' INNER JOIN 'albums' ON 'albums'.'id' = 'storage_lists'.'album_id' INNER JOIN 'music_storages' ON 'music_storages'.'id' = 'storage_lists'.'music_storage_id' WHERE (music_storages.name LIKE '%"+request_name+"%' AND albums.id = '"+album+"' AND music_storages.storage_type_id = '"+type+"' AND music_storages.company_id = '"+company+"') GROUP BY music_storages.id"
         respond_to do |format|
            format.html
            format.json { render json: { result: music_storages, title: title,  message: 'Nothing found by your request!' } }
        end
    end
    
   def music_storage_search_country

app/helpers/operation_controller_helper.rb
module OperationControllerHelper
end

app/views/operation_controller/artist_lists_report.html.erb
<h1>Storage Lists Report</h1>
<table class="table table-bordered table-striped">
    <thead class="thead-light">
        <tr>
            <th>id</th>
            <th>Artist name</th>
            <th>Artist-band</th>
            <th>Debut year</th>
            <th>End year</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Birth date</th>
            <th>Death date</th>
            <th>Country</th>
        </tr>
    </thead>
    <tbody>
        <% @artist_lists.each do |s| %>
        <tr>
            <td><%= s.id%></td>
            <td><%= s.artist_name%></td>
            <td>
             <% if s.type_band==1 -%>Band 
            <% else %>Single
            <% end -%>
            </td>
            <td><%= s.debut_year%></td>
            <td><%= s.end_year%></td>
            <td><%= s.first_name%></td>
            <td><%= s.last_name%></td>
            <td><%= s.birth_date%></td>
            <td><%= s.death_date%></td>
            <td><%= s.country_name%></td>
        </tr>
        <% end %>
    </tbody>
</table>
            
    
 
 

app/views/operation_controller/info_album_view.html.erb
<div class="row justify-content-center">
    <div class="col-11 name_field">
        <div class="row type">ALBUM</div>
        <div class="row  name_field"><%= @album.name%></div></div>
</div>
<div class="row justify-content-center">
    <div class="col-4">
        <%= image_tag @album.avatar.url(:thumb) if @album.avatar?%>
    </div>
    <div class="col-7">
        <div class="row description">
            <div class="col-3 ">ALBUM TYPE:</div>
            <div class="col-9"><%= @album.album_type.name%></div>
        </div>
        <div class="row description">
            <div class="col-3 ">GENRES:</div>
            <div class="col-9">
                <% @album.compositions.group(:genre_id).each do |s|%>
                <%= s.genre.name %>&nbsp;&nbsp;&nbsp;
                <%end%>
            </div>
        </div>
        <div class="row description">
            <div class="col-3 ">ARTISTS:</div>
            <div class="col-9">
                <% @album.artists.each do |s|%>
                <%= link_to s.name, info_artist_view_path(:artist_id => s.id)%>&nbsp;&nbsp;&nbsp;
                <% end %>
            </div>
        </div>
        <div class="row description">
            <div class="col-3 ">AUTHORS:</div>
            <div class="col-9">
                <% @album.persons.each do |s|%>
                <%= link_to s.first_name+" "+s.last_name, info_person_view_path(:person_id => s.id)%>&nbsp;&nbsp;&nbsp;
                <% end %>
            </div>
        </div>
        <div class="row description">
            <div class="col-3 ">LABEL:</div>
            <div class="col-9"><%= link_to @album.label.name, info_label_view_path(:label_id => @album.label.id)%></div>
        </div>
        <div class="row description">
            <div class="col-3 ">RELEASE DATE:</div>
            <div class="col-9"><%= @album.release_date%></div>
        </div>
        <div class="row description">
            <div class="col-3 ">MUSIC STORAGES:</div>
            <div class="col-9"><% @album.music_storages.each do |s|%>
                <%= link_to s.name+" ("+s.name+")", info_storage_view_path(:music_storage_id => s.id)%>&nbsp;&nbsp;&nbsp;
                <% end %></div>
        </div>
    </div>
</div>
<div class="row justify-content-center space">
    <div class="col-11">TRACKS:</div>
</div> 
<div class="row justify-content-center">
<div class="col-11">
<table class="table">
    <thead >
        <tr class="row">
            <th class="col-1">#</th>
            <th class="col-8">Name</th>
            <th class="col-3">Duration</th>
        </tr>
    </thead>
    <tbody>
    <% @album.composition_lists.order(:position_number).group(:composition_id).each do |s|%>
    <tr class="row">    
        <td class="col-1"><%=s.position_number %></td>
        <td class="col-8"><%= link_to s.composition.name, info_composition_view_path(:composition_id => s.composition.id)%></td>
        <td class="col-3"><%= s.composition.duration.strftime("%H:%M:%S")%></td>
    </tr>
    <% end %>
    </tbody>
    </table>
</div>
</div> 

app/views/operation_controller/info_composition_view.html.erb
<div class="row justify-content-center">
    <div class="col-11 ">
        <div class="row type">COMPOSITION</div>
        <div class="row name_field"><%= @composition.name %></div></div>
    </div>
    
    <div class="row justify-content-center">
        <div class="col-4">
            <%= image_tag("views/composition.png", size:"300") %>
        </div>
        <div class="col-7">
            <div class="row description">
                <div class="col-3 ">ARTISTS:</div>
                <div class="col-9">
                    <% @composition.artists.each do |s| %> 
                    <%= link_to s.name, info_artist_view_path(:artist_id => s.id)%>&nbsp;&nbsp;&nbsp;
                    <% end%>
                </div>
            </div>
            <div class="row description">
                <div class="col-3 ">GENRE:</div>
                <div class="col-9"><%= @composition.genre.name%></div>
            </div>
            <div class="row description">
                <div class="col-3 ">DURATION:</div>
                <div class="col-9"><%= @composition.duration.strftime("%H:%M:%S")%></div>
            </div>
            <div class="row description">
                <div class="col-3 ">RELEASE DATE:</div>
                <div class="col-9"><%= @composition.release_date%></div>
            </div>

            <div class="row description">
                <div class="col-3 ">AUTHORS:</div>
                <div class="col-9">
                    <% @composition.persons.each do |s| %>
                    <%= link_to s.first_name+" "+s.last_name, info_person_view_path(:person_id => s.id)%>&nbsp;&nbsp;&nbsp;
                    <% end %>    
                </div>
            </div>
            <div class="row description">
                <div class="col-3 ">CONSISTED IN ALBUMS:</div>
                <div class="col-9">
                    <% @composition.albums.each do |s| %>
                    <%= link_to s.name, info_album_view_path(:album_id => s.id) %>&nbsp;&nbsp;&nbsp;
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    
<div class="row justify-content-center space">
    <div class="col-11">LYRICS:</div>
</div>

<div class="row justify-content-center text-center">
    <div class="col-11"><%= simple_format(@composition.lyrics) %></div>
</div>
 

app/views/operation_controller/search.html.erb
<div id="search_block" class="wow fadeInUp" data-wow-offset="100" data-wow-duration="1.5s">
    <div class=" btn-group btn-group-lg btn-block" role="group">
        <%=button_tag "Album", id:"album_search_btn", title:"Search album", class:"btn btn-warning btn-block"%>
        <%=button_tag "Artist", id:"artist_search_btn", title:"Search artist", class:"btn btn-warning btn-block"%>
        <%=button_tag "Composition", id:"composition_search_btn", title:"Search composition", style:"background-color:'white'", class:"btn btn-warning btn-block active"%>
        <%=button_tag "Music Storage", id:"mus_stor_search_btn", title:"Search music storage", class:"btn btn-warning btn-block"%>
        <%=button_tag "Music Storage 2", id:"mus_stor_search_country_btn", title:"Search music stotages with country requests", class:"btn btn-warning btn-block"%>
    </div>
            
    <div id="search_form_block">
    <div id="composition_sf_block" class="sf_block_padd">
        <%= form_with id:'composition_search_form', method: :get, url: composition_search_path(format: :json) do |form|  %>
    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Name</div>
                <div class="col-9"><%= form.text_field :request_name, placeholder:"enter name of composition", class:"form-control form-control-lg" %></div>
            </div>
                    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Artist</div>
                <div class="col-9">
                    <select class="form-control form-control-lg" name="composition_artist_id" id="composition_artist_id">
                        <% Artist.order(:name).all.each do |s|%>
                            <option value=<%= s.id %>><%= s.name %></option>
                        <%end%>
                    </select>
                </div>
            </div>
                    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Genre</div>
                <div class="col-9">
                    <select class="form-control form-control-lg" name="composition_genre_id" id="composition_genre_id">
                        <% Genre.order(:name).all.each do |s|%>
                            <option value=<%= s.id %>><%= s.name %></option>
                        <%end%>
                    </select>
                </div>
            </div>
                        
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Date</div>
                <div class="col-9">
                    <div class="row">
                        <div class="col-6 col_date_from">
                        Date from<%= form.date_field :date_from, value:"1900-01-01", min:"1900-01-01", max: Time.now.strftime('%Y-%m-%d'), class:"form-control form-control-lg" %>
                        </div>
                        <div class="col-6 col_date_to">
                        Date to<%= form.date_field :date_to, value: Time.now.strftime('%Y-%m-%d'), min:"1900-01-01", max: Time.now.strftime('%Y-%m-%d'), class:"form-control form-control-lg" %>
                        </div>
                    </div>
                </div>
             </div>     
            
            <div class="row row_search_params">
            <div class="col"><%= form.submit "search", class:"btn btn-outline-warning btn-block rounded" %></div></div>
        <% end %>
    </div>
    
    <div id="album_sf_block" class="sf_block sf_block_padd" style="visibility: hidden">
        <%= form_with id:'album_search_form', method: :get, url: album_search_path(format: :json) do |form|  %>
    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Name</div>
                <div class="col-9"><%= form.text_field :request_name, placeholder:"enter name of album", class:"form-control form-control-lg" %></div>
            </div>
                    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Artist</div>
                <div class="col-9">
                    <select class="form-control form-control-lg" name="album_artist_id" id="album_artist_id">
                        <% Artist.order(:name).all.each do |s|%>
                            <option value=<%= s.id %>><%= s.name %></option>
                        <%end%>
                    </select>
                </div>
            </div>
                    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Label</div>
                <div class="col-9">
                    <select class="form-control form-control-lg" name="album_label_id" id="album_label_id">
                        <% Label.order(:name).all.each do |s|%>
                            <option value=<%= s.id %>><%= s.name %></option>
                        <%end%>
                    </select>
                </div>
            </div>
                        
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Release date</div>
                <div class="col-9">
                    <div class="row">
                        <div class="col-6 col_date_from">
                        Date from<%= form.date_field :date_from, value:"1900-01-01", min:"1900-01-01", max: Time.now.strftime('%Y-%m-%d'), class:"form-control form-control-lg" %>
                        </div>
                        <div class="col-6 col_date_to">
                        Date to<%= form.date_field :date_to, value: Time.now.strftime('%Y-%m-%d'), min:"1900-01-01", max: Time.now.strftime('%Y-%m-%d'), class:"form-control form-control-lg" %>
                        </div>
                    </div>
                </div>
             </div>     
            
            <div class="row row_search_params"><div class="col"><%= form.submit "search", class:"btn btn-outline-warning btn-block rounded" %></div></div>
        <% end %>
    </div>
    
    
    <div id="artist_sf_block" class="sf_block sf_block_padd" style="visibility: hidden">
        <%= form_with id:'artist_search_form', method: :get, url: artist_search_path(format: :json) do |form|  %>
    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Name</div>
                <div class="col-9"><%= form.text_field :request_name, placeholder:"enter name of artist", class:"form-control form-control-lg" %></div>
            </div>
                    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Type</div>
                <div class="col-9">
                    <div class="row">
                        <div class="col-6 col_date_from">Band<%= form.radio_button :artist_type, "1", checked:"checked", class:"form-control" %></div>
                        <div class="col-6 col_date_to">Single<%= form.radio_button :artist_type, "0", class:"form-control" %></div>
                    </div>
                </div>
            </div>
                    
                        
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Debut date</div>
                <div class="col-9">
                    <div class="row">
                        <div class="col-6 col_date_from">
                        Date from<%= form.date_field :date_from, value:"1900-01-01", min:"1900-01-01", max: Time.now.strftime('%Y-%m-%d'), class:"form-control form-control-lg" %>
                        </div>
                        <div class="col-6 col_date_to">
                        Date to<%= form.date_field :date_to, value: Time.now.strftime('%Y-%m-%d'), min:"1900-01-01", max: Time.now.strftime('%Y-%m-%d'), class:"form-control form-control-lg" %>
                        </div>
                    </div>
                </div>
             </div>     
            
            <div class="row row_search_params"><div class="col"><%= form.submit "search", class:"btn btn-outline-warning btn-block rounded" %></div></div>
        <% end %>
    </div>
    
    <div id="music_storage_sf_block" class="sf_block sf_block_padd" style="visibility: hidden">
        <%= form_with id:'music_storage_search_form', method: :get, url: music_storage_search_path(format: :json) do |form|  %>
    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Name</div>
                <div class="col-9"><%= form.text_field :request_name, placeholder:"enter name of music storage", class:"form-control form-control-lg" %></div>
            </div>
                    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Album</div>
                <div class="col-9">
                    <select class="form-control form-control-lg" name="music_storage_album_id" id="music_storage_album_id">
                        <% Album.order(:name).all.each do |s|%>
                            <option value=<%= s.id %>><%= s.name %></option>
                        <%end%>
                    </select>
                </div>
            </div>
                    
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Company</div>
                <div class="col-9">
                    <select class="form-control form-control-lg" name="music_storage_company_id" id="music_storage_company_id">
                        <% Company.order(:name).all.each do |s|%>
                            <option value=<%= s.id %>><%= s.name %></option>
                        <%end%>
                    </select>
                </div>
            </div>
            
            <div class="row row_search_params">
                <div class="col-3 col_search_params">Type</div>
                <div class="col-9">
                    <select class="form-control form-control-lg" name="music_storage_type_id" id="music_storage_type_id">
                        <% StorageType.order(:name).all.each do |s|%>
                            <option value=<%= s.id %>><%= s.name %></option>
                        <%end%>
                    </select>
                </div>
            </div>
            
            <div class="row row_search_params"><div class="col"><%= form.submit "search", class:"btn btn-outline-warning btn-block rounded" %></div></div>
        <% end %>
    </div>
    
    
    <div id="music_storage_sf_country_block" class="sf_block sf_block_padd" style="visibility: hidden">
        <%= form_with id:'music_storage_search_form_country', method: :get, url: music_storage_search_country_path(format: :json) do |form|  %>
            
            <div class="row row_search_params">
                <div class="col-5 col_search_params">Company country</div>
                <div class="col-7">
                    <select class="form-control form-control-lg" name="ms_company_country_id" id="ms_company_country_id">
                        <% Country.order(:name).all.each do |s|%>
                            <option value=<%= s.id %>><%= s.name %></option>
                        <%end%>
                    </select>
                </div>
            </div>
                    
            <div class="row row_search_params">
                <div class="col-5 col_search_params">Album label country</div>
                <div class="col-7">
                    <select class="form-control form-control-lg" name="ms_label_country_id" id="ms_label_country_id">
                        <% Country.order(:name).all.each do |s|%>
                            <option value=<%= s.id %>><%= s.name %></option>
                        <%end%>
                    </select>
                </div>
            </div>
                    
            <div class="row row_search_params">
                <div class="col-5 col_search_params">Production date</div>
                <div class="col-7">
                    <div class="row">
                        <div class="col-6 col_date_from">
                        Date from<%= form.date_field :date_from, value:"1900-01-01", min:"1900-01-01", max: Time.now.strftime('%Y-%m-%d'), class:"form-control form-control-lg" %>
                        </div>
                        <div class="col-6 col_date_to">
                        Date to<%= form.date_field :date_to, value: Time.now.strftime('%Y-%m-%d'), min:"1900-01-01", max: Time.now.strftime('%Y-%m-%d'), class:"form-control form-control-lg" %>
                        </div>
                    </div>
                </div>
             </div>     
            
            <div class="row row_search_params"><div class="col"><%= form.submit "search", class:"btn btn-outline-warning btn-block rounded" %></div></div>
        <% end %>
    </div>
    
    
    </div>
</div>
    <div id="search_result"></div>
    